### ISSUE TITLE
Line endings are CRLF

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/measles#29]
We should add `.gitattributes` similar to https://github.com/nextstrain/pathogen-repo-guide/pull/37 so that files use LF in the working directory. I haven't thoroughly checked which files are CRLF in this repo, but `phylogenetic/defualts/auspice_config*` are.

**Comment by victorlin** [comment]
Closed by d3c90b3cae647c4e447c8393f31de95aec358bee
