### ISSUE TITLE
Call measles genotypes during ingest and display on tree

### ISSUE THREAD

**Issue by trvrb** [nextstrain/measles#32]
With Nextclade dataset in hand, we should process sequences during ingest to assign a MeV genotype (like we do for SARS-CoV-2 and mpox). This MeV genotype should included as a coloring to the measles tree for both https://nextstrain.org/measles/N450 and https://nextstrain.org/measles/genome.

**Comment by kimandrews** [comment]
A preliminary version of this is currently available on [this branch](https://github.com/nextstrain/measles/compare/main...use-nextclade-dataset). It is a work in progress.

**Comment by kimandrews** [comment]
This was completed in https://github.com/nextstrain/measles/pull/36
