### ISSUE TITLE
Pad out page footer and update byline

### ISSUE THREAD

**Issue by trvrb** [nextstrain/measles#37]
### Footer

The current page footer is too minimal

>This work is made possible by the open sharing of genetic data by research groups from all over the world. We gratefully acknowledge their contributions.

It should start with:

>We gratefully acknowledge the authors, originating and submitting laboratories of the genetic sequences and metadata for sharing their work. Please note that although data generators have generously shared data in an open fashion, that does not mean there should be free license to publish on this data. Data generators should be cited where possible and collaborations should be sought in some circumstances. Please try to avoid scooping someone else's work. Reach out if uncertain.

And then it should have a brief description of the genome-level and N450 analyses like in mpox.

And then it should have a paragraph on the available curated sequences and metadata like in mpox.

### Byline

The byline should include 
>Enabled by data from [GenBank](https://www.ncbi.nlm.nih.gov/genbank/).

**Comment by kimandrews** [comment]
This was completed in https://github.com/nextstrain/measles/pull/39 and https://github.com/nextstrain/measles/pull/41
